version: '3.8'

services:
  api:
    image: mercari-build-training/app
    ports:
      - "9000:9000"
    environment:
      - FRONT_URL=http://localhost:3000
    networks:
      - mercari-network

  frontend:
    image: mercari-build-training/web
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:9000
    networks:
      - mercari-network

networks:
  mercari-network:
    driver: bridge